#!/usr/bin/env bash
set -euo pipefail

# Rewrite the merged release PR description to use permanent tag links.
#
# Usage:
#   update-release-pr-links.sh <version>
#
# When the release PR body is generated by create-release-pr.sh, the
# compare link points at the temporary release branch (whose name is
# decoupled from the version — see create-release-pr.sh) because the
# tag does not exist yet. Once the release workflow has cut the tag,
# the branch is deleted and the compare link goes stale. This script
# finds the merged release PR for the given version, reads its head
# branch from the GitHub API, and rewrites the compare link in its
# body to point at the permanent tag (vX.Y.Z).
#
# The rewrite is confined to the machine-generated changelog region of the
# body (layout: docs/guides/30-release.md), so a hand-written summary that
# happens to mention the release branch is left untouched.
#
# Environment variables:
#   GH_TOKEN - GitHub token for API access (required).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=release-pr-lookup.sh
source "${SCRIPT_DIR}/release-pr-lookup.sh"
# shellcheck source=release-summary.sh
source "${SCRIPT_DIR}/release-summary.sh"

main() {
    local version="$1"
    local pr_number branch body

    pr_number=$(find_release_pr "$version")
    if [ -z "$pr_number" ]; then
        echo "No merged release PR found for v${version}; nothing to rewrite."
        return 0
    fi

    branch=$(gh pr view "$pr_number" --json headRefName --jq '.headRefName')
    if [ -z "$branch" ]; then
        echo "::error::Could not read head branch for PR #${pr_number}." >&2
        return 1
    fi

    echo "Rewriting links on PR #${pr_number} (head ${branch})..."

    body=$(gh pr view "$pr_number" --json body --jq '.body')
    body=$(rewrite_compare_link "$body" "$branch" "$version")

    # printf, not echo: the body now opens with hand-written text, which
    # may start with `-n` and be swallowed as an echo option.
    printf '%s\n' "$body" | gh pr edit "$pr_number" --body-file -
    echo "Done."
}

# Point the compare link at the tag instead of the (now deleted) release
# branch, rewriting only the region below the marker. A body written before
# the marker existed carries no summary, so it is rewritten whole.
rewrite_compare_link() {
    local body="$1"
    local branch="$2"
    local version="$3"
    local marker head tail

    marker=$(changelog_marker)
    if [[ "$body" == *"$marker"* ]]; then
        head="${body%%"$marker"*}${marker}"
        tail="${body#*"$marker"}"
    else
        head=""
        tail="$body"
    fi

    printf '%s%s\n' "$head" \
        "$(printf '%s' "$tail" | sed "s|\.\.\.${branch}|...v${version}|g")"
}

main "$@"
