[package]
name = "wissel"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "Pick a browser every time you open a link"
repository = "https://github.com/x7c1/wissel"

[dependencies]
gio = "0.22.10"
gio-unix = "0.22.8"
gtk4 = { version = "0.11", features = ["v4_2"] }
libadwaita = { version = "0.9", features = ["v1_4"] }
